<a href="https://colab.research.google.com/github/ksn056/-_Additional_Data-Science-With-Python/blob/master/1_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
import spacy
import pandas as pd
from textblob import TextBlob

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

**1. Tokenization**

In [4]:
from nltk.tokenize import word_tokenize, sent_tokenize

text = "Natural Language Processing is amazing. It powers ChatGPT."

print("Word Tokenization:")
print(word_tokenize(text))

print("\nSentence Tokenization:")
print(sent_tokenize(text))

Word Tokenization:
['Natural', 'Language', 'Processing', 'is', 'amazing', '.', 'It', 'powers', 'ChatGPT', '.']

Sentence Tokenization:
['Natural Language Processing is amazing.', 'It powers ChatGPT.']

In [3]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

**2. Stemming and Lemmatization**

In [5]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ["running", "studies", "better"]

print("Stemming:")
print([stemmer.stem(w) for w in words])

print("\nLemmatization:")
print([lemmatizer.lemmatize(w) for w in words])

Stemming:
['run', 'studi', 'better']

Lemmatization:
['running', 'study', 'better']

**3. Named Entity Recognition (NER)**

In [6]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("Elon Musk founded SpaceX in the United States in 2002.")

print("Named Entities:")
for ent in doc.ents:
    print(ent.text, "-", ent.label_)

Named Entities:
Elon Musk - PERSON
the United States - GPE
2002 - DATE

**4. Sentiment Analysis**

In [7]:
text = "I love this product. It is absolutely fantastic!"

blob = TextBlob(text)
print("Sentiment Score:", blob.sentiment)

Sentiment Score: Sentiment(polarity=0.5, subjectivity=0.75)

In [9]:
text2 = "This is the worst experience ever."
print(TextBlob(text2).sentiment)

Sentiment(polarity=-1.0, subjectivity=1.0)

**5. Text Preprocessing**

In [10]:
data = pd.DataFrame({
    "text": [
        "I love NLP",
        "This is terrible",
        "Amazing product",
        "Worst experience ever"
    ]
})

data

                    text
0             I love NLP
1       This is terrible
2        Amazing product
3  Worst experience ever

**9 – Convert to Lowercase**

In [11]:
data["text"] = data["text"].str.lower()
data

                    text
0             i love nlp
1       this is terrible
2        amazing product
3  worst experience ever

**Remove Stopwords**

In [13]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in str(text).split() if word not in stop_words])

data['cleaned'] = data['text'].apply(lambda x: remove_stopwords(x))
data

                    text                cleaned
0             i love nlp               love nlp
1       this is terrible               terrible
2        amazing product        amazing product
3  worst experience ever  worst experience ever

**TF-IDF**

**6. Word Embeddings (Convert Text to Numbers)**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data["cleaned"])

print("TF-IDF Matrix:")
print(X.toarray())

TF-IDF Matrix:
[[0.         0.         0.         0.70710678 0.70710678 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.70710678 0.         0.         0.         0.         0.70710678
  0.         0.        ]
 [0.         0.57735027 0.57735027 0.         0.         0.
  0.         0.57735027]]

**7. Train a Simple Model**

In [15]:
from sklearn.linear_model import LogisticRegression

# Labels
y = [1, 0, 1, 0]

model = LogisticRegression()
model.fit(X, y)

print("Predictions:")
print(model.predict(X))

Predictions:
[1 0 1 0]

**8. Build a Simple Chatbot**

In [16]:
def chatbot(user_input):
    if "hello" in user_input.lower():
        return "Hi! How can I help you?"
    elif "nlp" in user_input.lower():
        return "NLP stands for Natural Language Processing."
    elif "bye" in user_input.lower():
        return "Goodbye!"
    else:
        return "I am still learning."

while True:
    user = input("You: ")
    if user.lower() == "exit":
        break
    print("Bot:", chatbot(user))

You: hi how are you
Bot: I am still learning.
You: kk
Bot: I am still learning.
You: exit

**Hugging Face Ready Model**

In [17]:
!pip install transformers

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
print(classifier("I love NLP"))

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9997692704200745}]

**N-GRAM**

In [18]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "Natural Language Processing is a fascinating field."
tokens = word_tokenize(text)

# Generate Bigrams (N=2)
bigrams_list = list(ngrams(tokens, 2))
print("Bigrams:", bigrams_list)

# Generate Trigrams (N=3)
trigrams_list = list(ngrams(tokens, 3))
print("Trigrams:", trigrams_list)

Bigrams: [('Natural', 'Language'), ('Language', 'Processing'), ('Processing', 'is'), ('is', 'a'), ('a', 'fascinating'), ('fascinating', 'field'), ('field', '.')]
Trigrams: [('Natural', 'Language', 'Processing'), ('Language', 'Processing', 'is'), ('Processing', 'is', 'a'), ('is', 'a', 'fascinating'), ('a', 'fascinating', 'field'), ('fascinating', 'field', '.')]

**Bag of Words (BoW)**

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

corpus = [
    'I love learning NLP',
    'I love programming',
    'NLP is fascinating and I love it'
]

# Create a CountVectorizer object
vectorizer = CountVectorizer()

# Fit the vectorizer to the corpus and transform the text data
X_bow = vectorizer.fit_transform(corpus)

# Get the feature names (words in the vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Convert the BoW matrix to a DataFrame for better readability
bow_df = pd.DataFrame(X_bow.toarray(), columns=feature_names)

print("Original Corpus:")
for doc in corpus:
    print(f"- {doc}")

print("\nBag of Words Representation (Counts):")
print(bow_df)

Original Corpus:
- I love learning NLP
- I love programming
- NLP is fascinating and I love it

Bag of Words Representation (Counts):
   and  fascinating  is  it  learning  love  nlp  programming
0    0            0   0   0         1     1    1            0
1    0            0   0   0         0     1    0            1
2    1            1   1   1         0     1    1            0